version: '3.8'

services:
  # Сервис для backend
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/app
    command: fastapi run core/main.py
    ports:
      - "8000:8000"
    networks:
      - app-network

  # Сервис для бота
  bot:
    build: .
    container_name: bot
    volumes:
      - .:/app
    command: python3 bot/bot.py
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
