"""Initial migration

Revision ID: 88f3d192cff4
Revises: 
Create Date: 2025-01-28 21:13:14.358175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f3d192cff4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('object_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('project_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'company_name')
    op.drop_column('items', 'project_name')
    op.drop_column('items', 'object_name')
    # ### end Alembic commands ###
