name: Deploy project to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/apps
            if [ ! -d act-builder ]; then
              git clone https://github.com/Ilya-Saldeckiy/tg-act-bot.git act-builder
            fi
            cd act-builder
            git pull origin master
            docker-compose down || true
            docker-compose up -d --build
